import type { Metadata } from "next";
import { type Dictionary, t } from "intlayer";

const metadataContent = {
  key: "page-metadata",
  content: {
    title: t({
      en: "Create Next App",
      fr: "Créer une application Next.js",
      es: "Crear una aplicación Next.js",
    }),
    description: t({
      en: "Generated by create next app",
      fr: "Généré par create next app",
      es: "Generado por create next app",
    }),
    keywords: t<string[]>({
      en: [
        "Internationalization",
        "Intlayer",
        "Next.js",
        "JavaScript",
        "React",
      ],
      fr: [
        "Internationalisation",
        "Intlayer",
        "Next.js",
        "JavaScript",
        "React",
      ],
      es: [
        "Internacionalización",
        "Intlayer",
        "Next.js",
        "JavaScript",
        "React",
      ],
    }),
  },
} satisfies Dictionary<Metadata>;

export default metadataContent;
